# Models package - Pydantic schemas for HenryAI API
# Organized by feature domain for clarity

# Import SupplementAnswer first since it's needed by other modules
from .documents import SupplementAnswer

from .resume import (
    ResumeParseRequest,
    Experience,
    ResumeProfile,
    ResumeCustomizeRequest,
    ResumeContent,
    SaveResumeRequest,
    UpdateResumeRequest,
    ResumeResponse,
    ResumeListResponse,
    ResumeLevelingRequest,
    ResumeLevelingResponse,
    LevelCompetency,
    LevelingGap,
    LevelingRecommendation,
    LevelMismatchWarning,
    RoleTypeBreakdown,
    ResumeChatMessage,
    ExtractedSkill,
    ResumeChatRequest,
    ResumeChatResponse,
    GenerateResumeFromChatRequest,
    GenerateResumeFromChatResponse,
)

from .jd import (
    JDAnalyzeRequest,
    JDAnalysis,
    URLExtractRequest,
    URLExtractResponse,
    JDSource,
    ConfidenceLabel,
    JDReconstructRequest,
    ProvisionalProfile,
    JDReconstructResponse,
)

from .documents import (
    # SupplementAnswer already imported above
    LevelingContext,
    DocumentsGenerateRequest,
    CoverLetterContent,
    GeneratedDocuments,
    CoverLetterGenerateRequest,
    PackageDownloadRequest,
    ResumeDownloadRequest,
    CoverLetterDownloadRequest,
    DocumentTypeForRefine,
    DocumentRefineRequest,
    DocumentChangeDetail,
    DocumentChangesSummary,
    DocumentRefineResponse,
)

from .interview import (
    InterviewQuestion,
    InterviewParseRequest,
    InterviewParseResponse,
    InterviewFeedbackRequest,
    DeliveryFeedback,
    InterviewFeedbackResponse,
    ThankYouRequest,
    ThankYouResponse,
    InterviewPrepRequest,
    RedFlagMitigation,
    QuestionToAsk,
    STARExample,
    LikelyQuestion,
    RecruiterScreenPrepContent,
    HiringManagerPrepContent,
    InterviewPrepResponse,
    IntroSellTemplateRequest,
    IntroSellTemplateResponse,
    IntroSellFeedbackRequest,
    IntroSellFeedbackResponse,
    TypedDebriefResponses,
    InterviewDebriefRequest,
    DimensionScores,
    WhatTheyShouldHaveSaid,
    InterviewDebriefResponse,
    DebriefContext,
    ConversationMessage,
    DebriefChatRequest,
    DebriefChatResponse,
    PrepGuideLikelyQuestion,
    PrepGuideStory,
    PrepGuideStrategyScenario,
    PrepGuideRequest,
    PrepGuideResponse,
    RegenerateIntroRequest,
    RegenerateIntroResponse,
    InterviewerRisk,
    InterviewerStrength,
    TailoredStory,
    InterviewerIntelRequest,
    InterviewerIntelResponse,
    DebriefExtractionRequest,
    DebriefExtractionResponse,
    PatternAnalysisResponse,
)

from .mock_interview import (
    StartMockInterviewRequest,
    FirstQuestionResponse,
    StartMockInterviewResponse,
    SubmitMockResponseRequest,
    SubmitMockResponseResponse,
    QuestionFeedbackResponse,
    NextQuestionRequest,
    MockSessionProgress,
    NextQuestionResponse,
    EndMockInterviewRequest,
    MockQuestionSummary,
    MockSessionFeedback,
    EndMockInterviewResponse,
    MockInterviewSessionSummary,
    ImprovementTrend,
    SessionHistoryResponse,
)

from .tracker import (
    Application,
    TasksPrioritizeRequest,
    Task,
    TasksPrioritizeResponse,
    OutcomeLogRequest,
    StrategyReviewRequest,
    StrategyReviewResponse,
    PriorityLevel,
    UrgencyLevel,
    PipelineStatus,
    PipelineTone,
    TrackerApplication,
    OneClickAction,
    PriorityAction,
    PipelineHealth,
    FocusModeAction,
    FocusMode,
    UISignals,
    TrackerIntelligenceRequest,
    ApplicationWithIntelligence,
    TrackerIntelligenceResponse,
    CalculateConfidenceRequest,
    ConfidenceFactors,
    CalculateConfidenceResponse,
)

from .network import (
    Contact,
    NetworkRecommendRequest,
    ContactRecommendation,
    NetworkRecommendResponse,
)

from .screening import (
    ScreeningQuestionsRequest,
    ScreeningQuestionResponse,
    ScreeningQuestionsResponse,
    ClarifyingQuestion,
    GenerateClarifyingQuestionsRequest,
    GenerateClarifyingQuestionsResponse,
    SupplementedExperience,
    ReanalyzeWithSupplementsRequest,
    ReanalyzeWithSupplementsResponse,
    ScreeningQuestionType,
    ScreeningRiskLevel,
    HonestyFlag,
    ScreeningQuestionInput,
    ScreeningQuestionsAnalyzeRequest,
    ScreeningQuestionAnalysis,
    ScreeningQuestionsAnalyzeResponse,
)

from .linkedin import (
    LinkedInExperience,
    LinkedInEducation,
    LinkedInParsedData,
    LinkedInUploadResponse,
    LinkedInAlignmentIssue,
    LinkedInAlignmentResponse,
    LinkedInOptimizeRequest,
    LinkedInExperienceOptimization,
    LinkedInOptimizeResponse,
)

from .hey_henry import (
    HeyHenryContext,
    HeyHenryMessage,
    HeyHenryAttachment,
    HeyHenryRequest,
    HeyHenryResponse,
)

from .common import (
    TTSRequest,
    SpeakRequest,
    ScreenshotExtractRequest,
    ExtractedJob,
    ScreenshotExtractResponse,
    FeedbackAcknowledgmentRequest,
)
